    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: vote-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: vote-app
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: auth-method
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-backup
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-backup
          persistentVolumeClaim:
              claimName: postgres-pvc