apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    name: result-svc
    app: vote-app
spec:
  type: NodePort
  ports:
  - name: "result-svc"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    name: result-app-pod
    app: vote-app
