apiVersion: v1
kind: Service
metadata:
  name: vote-svc
  labels:
    name: vote-svc
    app: vote-app
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    name: vote-app-pod
    app: vote-app
  
