apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: vote-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: vote-app
    spec:
      containers:
      - name: workewr-app
        image: dockersamples/examplevotingapp_worker
