{{- range .Values.deployments}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .globalSelector.SelectorApp }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      name: {{ .depSelector.SelectorName }}
      app: {{ .depSelector.SelectorApp }}
  template:
    metadata:
      name: {{ .podSelector.PodName }}
      labels:
        name: {{ .podSelector.SelectorName }}
        app: {{ .podSelector.SelectorApp }}
    spec:
      containers:
      - name: {{ .pod.containerName}}
        image: {{ .pod.containerImage}}
        env:
        {{- range .containerEnv }}
        - name: {{ .name }}
          value: {{ .value}}
        {{- end }}
       {{- if .configMapValue }}
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: auth-method
       {{- end }}
       {{- if .pod.containerPort }}
        ports:
        - containerPort: {{ .pod.containerPort}}
       {{- end }}
      {{- if .volume }}  
        volumeMounts:
          - name: postgres-backup
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-backup
          persistentVolumeClaim:
              claimName: postgres-pvc
      {{- end }}
---
{{- end }}

